using OCPPaymentSystemAPI.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OCPPaymentSystemAPI.Documents
{
    public class MemoPdfDocument : IDocument
    {
        private readonly MemoPdfModel _model;

        public MemoPdfDocument(MemoPdfModel model)
        {
            _model = model;
        }

        public DocumentMetadata GetMetadata()
        {
            return DocumentMetadata.Default;
        }

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);

                page.Margin(30);

                page.DefaultTextStyle(x =>
                    x.FontSize(10));

                page.Header()
                    .AlignCenter()
                    .Text("MEMORANDUM")
                    .Bold()
                    .FontSize(18);

                page.Content()
                    .Column(column =>
                    {
                        column.Spacing(6);

                        AddItem(column, "Memo No", _model.MemoNo);
                        AddItem(column, "Date", _model.MemoDate.ToString("dd MMM yyyy"));
                        AddItem(column, "Company", _model.CompanyName);
                        AddItem(column, "Supplier", _model.SupplierName);
                        AddItem(column, "Invoice", _model.InvoiceNo);
                        AddItem(column, "Amount", _model.Amount.ToString("N2"));
                        AddItem(column, "Bank", _model.BankName);
                        AddItem(column, "Account No", _model.AccountNo);
                        AddItem(column, "Account Name", _model.AccountName);

                        column.Item().PaddingTop(15);

                        column.Item().Text("Remarks")
                            .Bold();

                        column.Item()
                            .Border(1)
                            .Padding(8)
                            .Text(_model.Remarks);

                        column.Item().PaddingTop(30);

                        column.Item().Row(row =>
                        {
                            row.RelativeItem()
                                .Column(col =>
                                {
                                    col.Item().Text("Prepared By");

                                    col.Item().Height(50);

                                    col.Item().Text(_model.CreatedBy)
                                        .Bold();

                                    col.Item().Text(
                                        _model.CreatedOn.ToString("dd MMM yyyy"));
                                });

                            row.RelativeItem()
                                .Column(col =>
                                {
                                    col.Item().Text("Approved By");

                                    col.Item().Height(50);

                                    col.Item().Text(_model.ApprovedBy)
                                        .Bold();

                                    if (_model.ApprovedOn.HasValue)
                                    {
                                        col.Item().Text(
                                            _model.ApprovedOn.Value.ToString("dd MMM yyyy"));
                                    }
                                });
                        });
                    });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by OCP Payment System");
            });
        }

        private static void AddItem(
            ColumnDescriptor column,
            string title,
            string value)
        {
            column.Item().Row(row =>
            {
                row.ConstantItem(140)
                    .Text(title)
                    .SemiBold();

                row.RelativeItem()
                    .Text(": " + value);
            });
        }
    }
}