using OCPPaymentSystemAPI.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OCPPaymentSystemAPI.Documents
{
    public class MemoPdfGenerator
    {
        public byte[] Generate(MemoPdfModel model)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);

                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header()
                        .AlignCenter()
                        .Text("MEMORANDUM")
                        .Bold()
                        .FontSize(16);

                    page.Content().Column(col =>
                    {
                        col.Spacing(6);

                        AddRow(col, "Memo No", model.MemoNo);
                        AddRow(col, "Date", model.MemoDate.ToString("dd MMM yyyy"));
                        AddRow(col, "Company", model.CompanyName);
                        AddRow(col, "Supplier", model.SupplierName);
                        AddRow(col, "Invoice", model.InvoiceNo);
                        AddRow(col, "Amount", model.Amount.ToString("N2"));
                        AddRow(col, "Bank", model.BankName);
                        AddRow(col, "Account No", model.AccountNo);
                        AddRow(col, "Account Name", model.AccountName);

                        col.Item().PaddingTop(15);

                        col.Item().Text("Remarks").Bold();

                        col.Item().Border(1).Padding(8).MinHeight(70)
                            .Text(model.Remarks);

                        col.Item().PaddingTop(30);

                        col.Item().Row(r =>
                        {
                            r.RelativeItem().Column(c =>
                            {
                                c.Item().Text("Prepared By");
                                c.Item().Height(50);
                                c.Item().Text(model.CreatedBy).Bold();

                                if (model.CreatedOn != DateTime.MinValue)
                                    c.Item().Text(model.CreatedOn.ToString("dd MMM yyyy HH:mm"));
                            });

                            r.RelativeItem().Column(c =>
                            {
                                c.Item().Text("Approved By (CFO)");
                                c.Item().Height(50);
                                c.Item().Text(model.ApprovedBy).Bold();

                                if (model.ApprovedOn.HasValue)
                                    c.Item().Text(model.ApprovedOn.Value.ToString("dd MMM yyyy HH:mm"));
                            });
                        });
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by OCP Payment System");
                });
            }).GeneratePdf();
        }

        private static void AddRow(ColumnDescriptor col, string title, string value)
        {
            col.Item().Row(r =>
            {
                r.ConstantItem(120).Text(title).SemiBold();
                r.RelativeItem().Text(": " + value);
            });
        }
    }
}